name: Test Project
# trigger events
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Get code # dl code from repo
          uses: actions/checkout # identifier; can specify version ex: actions/checkout@v2
        - name: Install nodeJS
          uses: actions/setup-@node@v3
          with: 
            node-version: '18'
        - name: Install dependencies
          run: npm ci
        - name: Run tests
          run: npm test  